// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_2ktlEAGuFFlVlQkcbpfhH_FkU9Kdiwc',
    appId: '1:182193040039:web:0fbeaa511fed6dbcddc982',
    messagingSenderId: '182193040039',
    projectId: 'ngo-connect-955d6',
    authDomain: 'ngo-connect-955d6.firebaseapp.com',
    storageBucket: 'ngo-connect-955d6.firebasestorage.app',
    measurementId: 'G-KH16EJ9N1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSl0GDVCh3P94Xw-UqfyM3cvy3_C9dFA',
    appId: '1:182193040039:android:29ad92ed750cf023ddc982',
    messagingSenderId: '182193040039',
    projectId: 'ngo-connect-955d6',
    storageBucket: 'ngo-connect-955d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACyNHIvYJ8PWVya1qXamoTMFXtlU2J0J4',
    appId: '1:182193040039:ios:417582948988b61eddc982',
    messagingSenderId: '182193040039',
    projectId: 'ngo-connect-955d6',
    storageBucket: 'ngo-connect-955d6.firebasestorage.app',
    iosClientId: '182193040039-39geomblja1vkitqbcg9njfg3l7ghbj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACyNHIvYJ8PWVya1qXamoTMFXtlU2J0J4',
    appId: '1:182193040039:ios:417582948988b61eddc982',
    messagingSenderId: '182193040039',
    projectId: 'ngo-connect-955d6',
    storageBucket: 'ngo-connect-955d6.firebasestorage.app',
    iosClientId: '182193040039-39geomblja1vkitqbcg9njfg3l7ghbj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_2ktlEAGuFFlVlQkcbpfhH_FkU9Kdiwc',
    appId: '1:182193040039:web:299276114127427fddc982',
    messagingSenderId: '182193040039',
    projectId: 'ngo-connect-955d6',
    authDomain: 'ngo-connect-955d6.firebaseapp.com',
    storageBucket: 'ngo-connect-955d6.firebasestorage.app',
    measurementId: 'G-YNRG4XC8HW',
  );

}